<?xml version="1.0" encoding="utf-8"?><Database Name="Capping" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tbOpUser" Member="tbOpUser">
    <Type Name="tbOpUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OpType" Type="System.Int32" DbType="Int" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UserCode" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>